import time
import turtle
import random
from tkinter import*

win=Tk()
win.title("❁´◡`❁")
win.geometry("100x100")
l=Label(win,text="Ganpatti bappa....")
l.grid(column=0,row=0)
E1= Entry(win)
E1.grid(column=0,row=1)
print(E1)
 


def submit():
    x=E1.get()
    if str(x.upper())=="MORYA":
        win.destroy()
        screen = turtle.Screen()
        turtle.setup(800, 800)
        screen.title("Ganpati bappa morya")
        screen.bgcolor("black")
        t = turtle.Turtle()
        t.color("yellow")
        t.begin_fill()
        t.speed(10)

        t.up()
        t.goto(0,320)
        t.pd()
        t.circle(3)
        t.end_fill()
        t.up()
        t.goto(2,314)
        t.right(45)
        t.begin_fill()
        t.pd()
        t.circle(65,35)
        t.circle(-75,40)
        t.circle(-25,160)
        t.circle(-35,40)
        t.forward(37)
        t.circle(-3,180)
        t.forward(35)
        t.circle(33,40)
        t.circle(20,160)
        t.circle(74,40)
        t.circle(-64,35)
        t.end_fill()
        t.up()
        t.home()
        t.goto(36,286)
        t.pd()
        t.begin_fill()
        t.right(10)
        t.circle(-48,40)
        t.circle(-12,180)
        t.circle(-48,40)
        t.end_fill()
        t.up()
        t.home()
        t.goto(-86,250)
        t.pd()
        t.left(90)
        t.begin_fill()
        t.circle(-85,30)
        t.right(90)
        t.circle(-85,30)
        t.right(176)
        t.circle(100,30)
        t.left(90)
        t.circle(95,30)
        t.end_fill()
        t.up()
        t.right(90)
        t.backward(17)
        t.right(90)
        t.pd()
        t.begin_fill()
        t.circle(-65,30)
        t.right(90)
        t.circle(-55,30)
        t.right(176)
        t.circle(65,30)
        t.left(90)
        t.circle(55,30)
        t.end_fill()
        t.up()
        t.home()
        t.goto(-106,210)
        t.pd()
        t.begin_fill()
        t.left(45)
        t.circle(-96,90)
        t.circle(3,175)
        t.circle(90,110)
        t.end_fill()
        x=-26
        for i in range(3):
            t.up()
            t.home()
            t.goto(x,270)
            t.pd()
            t.begin_fill()
            t.left(90)
            t.circle(45,90)
            t.circle(3,175)
            t.circle(-50,95)
            t.end_fill()
            x+=20
        x2=-80
        c=2
        for i in range(6):
            t.up()
            t.home()
            t.goto(x2,190)
            t.pd()
            t.begin_fill()
            t.circle(c)
            x2+=20
            c+=2
            t.end_fill()
        t.up()
        t.forward(90)
        t.pd()
        t.left(90)
        t.begin_fill()
        t.circle(30,180)
        t.end_fill()
        t.up()
        t.left(45)
        t.forward(40)
        t.pd()
        t.begin_fill()
        t.circle(-90,130)
        t.circle(65,270)
        t.circle(-6,180)
        t.circle(3,100)
        t.circle(-8,200)
        t.left(90)
        t.circle(-70,270)
        t.circle(93,139)
        t.end_fill()
        t.up()
        t.goto(-70,160)
        t.pd()
        t.begin_fill()
        t.circle(80,200)
        t.circle(-15,90)
        t.circle(60,200)
        t.circle(3,175)
        t.circle(-56,200)
        t.circle(13,90)
        t.circle(-75,200)
        t.end_fill()
        t.up()
        t.home()
        t.goto(3,140)
        t.pd()
        t.begin_fill()
        t.left(90)
        t.circle(-23,180)
        t.circle(3,175)
        t.circle(25,180)
        t.hideturtle()
        t.circle(9)
        t.end_fill()
        t.begin_fill()
        t.color("black")
        t.circle(4)
        t.end_fill()
        x3=70
        t.color("yellow")
        for i in range(3):
            t.up()
            t.home()
            t.left(90)
            t.goto(-50,x3)
            t.pd()
            t.begin_fill()
            t.circle(45,90)
            t.circle(3,175)
            t.circle(-50,95)
            t.end_fill()
            x3-=20
   
        
b=Button(win,text="Submit",command=submit)
b.grid(column=0,row=3)

